### ISSUE TITLE
failed to execute 'postmessage' on 'broadcastchannel' channel is closed

### ISSUE THREAD

**Issue by mimre73** [Romainlg29/use-broadcast#5] opened 2024-05-28 09:52 UTC
When i am in production i get this error

failed to execute 'postmessage' on 'broadcastchannel' channel is closed

**Comment by Romainlg29** [comment] 2024-05-28 15:53
Hi @mimre73 

Can you give more details?
(Mostly, how to reproduce this.)

**Comment by Romainlg29** [comment] 2024-06-18 17:53
Closing.

**Closed as completed by Romainlg29** 2024-06-18 17:53 UTC

**Comment by eriCCsan** [comment] 2025-02-10 12:14
@Romainlg29 I'm encountering the same error right before switching the website for login. The flow is straightforward:

1. Click on login
2. Error occurs
3. Redirect to login mask (different URL)
4. Login
5. Redirect back

The full error message in my console is:

```
Uncaught InvalidStateError: Failed to execute 'postMessage' on 'BroadcastChannel': Channel is closed
    at onClose (:5173/node_modules/.vite/deps/use-broadcast-ts.js?v=4caad429:152:13)
    at Object.navigate (:5173/node_modules/.vite/deps/chunk-CVUU3NSO.js?v=4caad429:2539:9)
    at UserManager._signinStart (:5173/node_modules/.vite/deps/chunk-CVUU3NSO.js?v=4caad429:3107:27)
    at async UserManager.signinRedirect (:5173/node_modules/.vite/deps/chunk-CVUU3NSO.js?v=4caad429:2804:5)
    at async Object.signinRedirect (:5173/node_modules/.vite/deps/react-oidc-context.js?v=4caad429:147:22)
    at async :5173/node_modules/.vite/deps/react-oidc-context.js?v=4caad429:254:9
onClose @ use-broadcast-ts.js?v=4caad429:152
navigate @ chunk-CVUU3NSO.js?v=4caad429:2539
_signinStart @ chunk-CVUU3NSO.js?v=4caad429:3107
```

I believe the issue is here:

```
...
const onClose = () => {
    channel.postMessage({
      action: "close",
      id
    });
...
```

It looks like the channel is already closed and in an invalid state when `postMessage` is called. Would it be necessary to check if the channel is open before posting the message?

**Comment by eriCCsan** [comment] 2025-02-10 14:14
@Romainlg29, I investigated further and suggest wrapping the following line: 

- https://github.com/Romainlg29/use-broadcast/blob/main/src/shared.ts#L313

in a `try` and `catch` block. I believe the error occurs when a user attempts to navigate to a different website, causing the channel to close elsewhere. 

As an alternative, manually triggering the closure of the channel could also be a viable solution. However, I strongly recommend wrapping this in a `try` and `catch` block and logging a warning to prevent a critical error from appearing in the browser console, which currently results in a disruptive red error message.

**Comment by Romainlg29** [comment] 2025-02-13 17:22
Hi @eriCCsan ,

L'll take a look at this on the weekend.

We cannot check if the broadcast channel is already closed.
Giving an option to manually close the channel can be an option but i'm not sure if this is the right path.
On the other hand, using try / catch is a bit hacky but can be a temporary solution... Maybe adding an option to silent the warning message?

What is the best for you?

**Comment by eriCCsan** [comment] 2025-02-13 18:43
Yes, I think this is a bit hacky, whether or not silencing the message
would be a good option. In this scenario, it only happens when I navigate
to a different website, which causes the channel to be closed abruptly.

Maybe we could make the close function public and call it in an await
manner, assuming the channel is closed anyway. Both options seem viable.

I prefer whichever option results in the simplest logic.

**Comment by Romainlg29** [comment] 2025-02-16 20:56
Hi @eriCCsan ,

I'm trying to reproduce the issue, but I not getting any error...
How did you get the error?

I've tested by adding a `<a href...>` tag and with `window.open("...", "_self");`, but I'm getting no errors in the console...
If you have a small code sample to reproduce the error, it would be awesome!

Thank you.

**Comment by eriCCsan** [comment] 2025-02-17 14:21
@Romainlg29 
I use `oidc-context-ts` and `oidc-client-ts`. Whenever the user isn't authorized, they are redirected to my OIDC login page to sign in. The error occurs right before this redirection.

I haven't found the exact implementation, but I would bet they handle it by setting `window.location.href` to a different URL. I also suspect that the process is asynchronous, causing the channel to close abruptly without the different parts being aware of each other.

I can't provide a full example because my setup consists of too many files and is quite complex.

**Comment by Romainlg29** [comment] 2025-02-23 10:28
@eriCCsan 
I have tried different ways to reproduce, but I couldn't...
Maybe that's a browser difference?

So, I pushed a fix with a try/catch block to silence the error, this shouldn't cause any errors as when you're redirected to the page, the channel will be created again.

**Comment by eriCCsan** [comment] 2025-02-25 20:19
I've tried the fix, and I love it. Thank you very much!
